---
title: "Lesson 6 examples--Random Forests"
author: "Abra Brisbin"
date: "2023-12-15"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(caret)
library(dplyr)

library(randomForest)

library(ggformula)

#library(mlbench) # The sonar data are also in this package, and can be accessed with
#data(Sonar)
```

## Random Forests

```{r}

sonar = read_csv("Sonar_rock_metal.csv", col_names = F)
head(sonar)
#help(Sonar) # View the data documentation in the mlbench package

```

```{r}

set.seed(88)
ctrl = trainControl(method = "cv", number = 5)
fit_rf = train(X61 ~ ., 
             data = sonar,
             method = "rf",
             tuneGrid = expand.grid(mtry = c(6, 7, 8, 9, 10, 60)),
             trControl = ctrl)

fit_rf

```

```{r}

plot(fit_rf$finalModel)
legend("topright", 
       colnames(fit_rf$finalModel$err.rate), 
       col = 1:3, lty = 1:3)

```

```{r}
predict(fit_rf, type = "prob")
```

```{r}

varImp(fit_rf)

```

```{r}

varImpPlot(fit_rf$finalModel)

```

## Partial Dependence Plots
```{r}

partialPlot(fit_sonar$finalModel, x.var = X11, 
            pred.data = as.data.frame(sonar), 
            which.class = "M")

```

```{r}

partialPlot(fit_sonar$finalModel, x.var = X11, 
            pred.data = as.data.frame(sonar), 
            which.class = "M")

```

```{r}

source("gf_partialPlot.R")
gf_partialPlot(fit_sonar, sonar, x.var = "X11", which.class = "M") %>%
  gf_labs(caption = "We can pipe the graph into other functions, like in other ggformula graphs.")

```

```{r}

gf_violin(X11 ~ X61, data = sonar, 
          draw_quantiles = c(.25, .5, .75))

```

## Joint effect of 2 variables
This version is hard to read:
```{r}
# [1] gives probablility of being metal

sonar2 <- sonar %>%
  mutate(example_preds = predict(fit_sonar, sonar, type = "prob")[,1]) 

sonar2 %>%
  gf_point(example_preds ~ X11, col =~ X12) %>%
  gf_refine(scale_color_gradient(low = "darkblue", high = "red"))

```
## Holding other variables constant
Example of how `across` works
```{r}
x=data.frame(a=1:3, b=4:6, c = 7:9)
x %>%
  summarise(across(everything(), median))

x %>%
  mutate(across(everything(), median))

x %>%
  mutate(across(c(-b), median))

```
```{r}

sonar2 <- sonar %>%
  mutate(across(c(-X11, -X12, -X61), median))

```
The above is equivalent to:
```{r, eval = F}

sonar2 <- sonar %>%
  mutate(X1 = median(X1),
         X2 = median(X2),
         X3 = median(X3),
         ...
         X60 = median(X60))

```

Include the predicted probability, and graph it:
```{r}

sonar2 <- sonar2 %>%
  mutate(example_preds = predict(fit_sonar, sonar2, type = "prob")[,1]) #probablility of being metal

sonar2 %>%
  gf_point(example_preds ~ X11, col =~ X12) %>%
  gf_refine(scale_color_gradient(low = "darkblue", high = "red"))

```

## Double CV
```{r}

set.seed(88)
n = nrow(sonar)
n_outer_folds = 5

sonar$X61 = factor(sonar$X61)
cv_pred = factor(vector(length = n), 
                 levels = levels(sonar$X61))

groups = rep(1:n_outer_folds, length = n)
cv_groups = sample(groups, n)


for(ii in 1:n_outer_folds){
  in_test = (cv_groups == ii)
  in_train = (cv_groups != ii)
  
  
  ctrl = trainControl(method = "cv", number = 5)
  fit_rf_DCV = train(X61 ~ ., 
              data = sonar[in_train, ],
              method = "rf",
              tuneGrid = expand.grid(mtry = c(6, 7, 8, 9, 
                                              10, 60)),
              trControl = ctrl)

  
  # "Frankenstein" vector of predictions
  cv_pred[in_test] = predict(fit_rf_DCV, 
                             newdata = sonar[in_test, ])
  
}

conf_mat = table(cv_pred, sonar$X61)
conf_mat

sum(diag(conf_mat))/n # This is the most honest 
                      # assessment of accuracy

```

No-information rate is 0.534, so our model is a big improvement.
```{r}
table(sonar$X61)/n
```